/*
 * Онлайн библиотека песен
 *
 * тестовое задание
 *
 * API version: 0.0.1
 * Contact: apa.birds@mail.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddGroup",
		strings.ToUpper("Post"),
		"/group",
		AddGroup,
	},

	Route{
		"GetGroup",
		strings.ToUpper("Get"),
		"/group",
		GetGroup,
	},

	Route{
		"UpdateGroup",
		strings.ToUpper("Put"),
		"/group",
		UpdateGroup,
	},

	Route{
		"AddSong",
		strings.ToUpper("Post"),
		"/song",
		AddSong,
	},

	Route{
		"DeleteSong",
		strings.ToUpper("Delete"),
		"/song",
		DeleteSong,
	},

	Route{
		"GetSong",
		strings.ToUpper("Get"),
		"/song",
		GetSong,
	},

	Route{
		"SongList",
		strings.ToUpper("Get"),
		"/songList",
		SongList,
	},

	Route{
		"UpdateSong",
		strings.ToUpper("Put"),
		"/song",
		UpdateSong,
	},
}
